name: Publish to TestPyPI

on:
  push:
    branches:
      - 'feature/actions_deploy_pypi'
      #- 'release*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test-sdist-and-wheels:
    uses: glotzerlab/signac/.github/workflows/publish-packages.yml@feature/actions_deploy_pypi
  deploy-pypi:
    runs-on: ubuntu-latest
    needs: build-and-test-sdist-and-wheels
    steps:
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        password: FAKE
        #password: ${{ secrets.TEST_PYPI_API_TOKEN }}
