name: Publish packages

on:
  # TODO: Temporary for testing, change this to be on a tag.
  push:
    branches:
      - 'feature/actions_deploy_pypi'

  # trigger on request
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
        check-latest: true
    - name: Install dependencies
      run: |
        # We must explicitly install the requirements so that we can force
        # installation of the local wheel below (in case the version conflicts
        # with published wheels, typically only possible during testing).
        # TODO: We can probably remove this when finalizing the workflow.
        python -m pip install -r requirements.txt
        python -m pip install -r requirements/requirements-test.txt
        python -m pip install -r requirements/requirements-test-optional.txt
    - name: Install pypa/build
      run:
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run:
        python -m build --sdist --wheel --outdir dist/ .
    - name: Install wheel
      run:
        # TODO: When we remove the install of requirements.txt above we must
        # also remove --no-index here, and we should probably include -U as
        # well. Note that the resulting job will fail if it is ever run on an
        # preexisting tag with an uploaded PyPI wheel since that will be
        # preferred to the local one.
        python -m pip install signac --progress-bar off --no-index -f dist/
    - name: Run MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
    - name: Run Redis
      uses: supercharge/redis-github-action@1.4.0
    - name: Test with pytest
      run:
        python -m pytest -v tests/
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
